name: Tauri Release (Windows)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 0.1.0). Leave empty to use tauri.conf.json package.version"
        required: false
        default: ""
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Tauri CLI (v1)
        run: cargo install tauri-cli --version "^1"

      - name: Build and create GitHub Release (Windows)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: .
          tagName: v__VERSION__
          releaseName: "SEA U LO-RA Dashboard v__VERSION__"
          releaseBody: "Auto-generated release for v__VERSION__"
          releaseDraft: true
          prerelease: false